name: Update TOC interface version(s)

on:
  schedule:
    - cron: '* 12 * * *'

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Clone project
        uses: actions/checkout@v3

      - name: Update TOC interface version(s)
        uses: p3lim/toc-interface-updater@v3

      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          author_name: Pingumania
          author_email: pingumania@users.noreply.github.com
          message: 'Update TOC interface version(s)'
          add: '.'
